name = "worker-name"
compatibility_date = "2025-04-25"

[build]
command = "npm run build" # Este comando ejecuta tu build (por ejemplo, vite build)

[env.production]
account_id = "tu-account-id"
workers_dev = false
route = "https://tudominio.com/*" # La ruta a la que se va a asociar el Worker
zone_id = "tu-zone-id"

[[deployments]]
path = "./dist"
